sharepet/config/routes.rb
Sharepet::Application.routes.draw do

  match '/auth/:provider/callback', to: 'sessions#createTwitter'

  get 'animals/twitter', to: 'animals#tweet_animal'

  get "users/new"
  get "sessions/new"

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  match "/animals/:id" => "animals#new", :as => :interested

  resources :users

  get "welcome/index"

  resources :animals, path: :animal

  root :to => 'welcome#index'
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  resources :animals, only: [:index, :new, :create, :destroy]

end

sharepet/app/models/animal.rb
class Animal < ActiveRecord::Base

  attr_accessible :age, :animalType, :breed, :name, :adopted, :attachment, :donor, :address, :latitude, :logitude, :interested
  
  # scope :by_breed, -> breed { where( :breed => breed) }
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader
  scope :by_breed, -> breed { where( "lower(animals.breed) like lower(?)", "%#{breed}%") }
  scope :by_address, -> address { where( "lower(animals.address) like lower(?)", "%#{address}%") }
  scope :only_available, -> { where(adopted: false) }



  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

end

sharepet/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  has_scope :by_breed
  has_scope :by_address
  has_scope :only_available, :type => :boolean, allow_blank: false
  # GET /animals
  # GET /animals.json

  def index(filter=nil)
    @animals = Animal.all.sort_by{|e| e[:name]}

    @filtered = apply_scopes(Animal).all.sort_by{|e| e[:name]}
    @available = @filtered.find_all { |animal| animal.adopted == true }
  
   if params[:search].present?
        @animals = Animal.near(params[:search], 50, :order => :distance)
    else
        @animals = Animal.all
    end
  end

  def tweet_animal
    string = "Adote esse animal domestico: " + "http://0.0.0.0:3000/animals/"

    current_user.tweet(string)
    redirect_to "/animals"
  end


  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/new
  # GET /animals/new.json
  def new
    @animal = Animal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(params[:animal])
    if current_user
      @animal.donor = current_user.username
    end

    respond_to do |format|
      if @animal.save
        # Tell the ReportMailer to send a report email after save
        if current_user
          if current_user.email
            UserMailer.sharingPetMail(@animal,current_user.email).deliver
          end
        end
        format.html { redirect_to @animal, notice: 'Pet was successfully created.' }
        
        format.json { render json: @animal, status: :created, location: @animal }
      else
        format.html { render action: "new" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.json
  def update
    @animal = Animal.find(params[:id])

    respond_to do |format|
      if @animal.update_attributes(params[:animal])
        format.html { redirect_to @animal}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url }
      format.json { head :no_content }
    end
  end

  def add_interested_user
    # @animal = Animal.find(params[:id])
    # @animal.interested = current_user.username

    # respond_to do |format|
    #   if @animal.update_attributes(params[:animal])
    #     format.html { redirect_to @animal}
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @animal.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  private

  # A list of the param names that can be used for filtering the Product list
  def filtering_params(params)
    params.slice(:status, :location, :starts_with)
  end

end

sharepet/app/helpers/animals_helper.rb
module AnimalsHelper

	def resolve_boolean_parameter resource, attribute, options = {}
	  default = options.delete(:default)
	  return default unless params[:utf8]

	  return params[resource][attribute] == "true"
	end

end

sharepet/app/views/animals/_form.html.erb
<%= form_for(@animal, :html => {:multipart => true}) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
     <div class="input-field col s6">
      <%= f.label :name %>
      <%= f.text_field :name, :value => "Pet" %>
    </div>

    <div class="input-field col s6">
      <%= f.label "Specie" %>
      <%= f.text_field :animalType %>
    </div>

  <div class="input-field col s6">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  
    <div class="input-field col s6">
      <%= f.label :breed %>
      <%= f.text_field :breed, :value => "Pet" %>
    </div>

</div><div class="row">
      <div class="input-field col s5 ">
        <%= f.label :age %>
        <%= f.number_field :age, :min => 0, :value => 0 %>
      </div> 


      <div class="file-field input-field col s5">
        <div class="btn">
          <span>File</span>
          <%= f.file_field :attachment, :accept=>"image/png,image/gif,image/jpeg"%>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text" placeholder=<%= @animal.attachment %> >
        </div>
      </div>
      <!-- <%= f.file_field :attachment %> -->
    </div>

  <div >
    <button class="btn waves-effect waves-light" type="submit" name="action" onclick="Materialize.toast('Successfully Submited!', 4000)">Submit
      <i class="material-icons right">send</i>
    </button>
  </div>
<% end %>

sharepet/app/views/animals/edit.html.erb
<div class="center">
  <h1>Updating pet</h1>

  <%= form_for(@animal) do |f| %>
    <% if @animal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

        <ul>
        <% @animal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
     <div class="input-field col s6">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="input-field col s6">
      <%= f.label "Specie" %>
      <%= f.text_field :animalType %>
    </div>

    <div class="input-field col s6">
      <%= f.label :breed %>
      <%= f.text_field :breed %>
    </div>

</div><div class="row">
      <div class="input-field col s5 ">
        <%= f.label :age %>
        <%= f.number_field :age %>
      </div> 


      <div class="file-field input-field col s5">
        <div class="btn">
          <span>File</span>
          <%= f.file_field :attachment, :accept=>"image/png,image/gif,image/jpeg"%>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text" placeholder=<%= @animal.attachment %> >
        </div>
      </div>
      <!-- <%= f.file_field :attachment %> -->
    </div>


      <div class="switch col s2">
        <label>
          Available
          <%= f.check_box :adopted , :type=>"checkbox"%>
          <span class="lever"></span>
          Adopted
        </label>
      </div>
      <br><br>

    <div >
      <button class="btn waves-effect waves-light" type="submit" name="action" onclick="Materialize.toast('Successfully Submited!', 4000)">Submit
        <i class="material-icons right">send</i>
      </button>
    </div>
  <% end %>


  <br>
  <%= link_to 'Back', @animal ,:class=>"btn waves-effect waves-orange red"%>
</div>

sharepet/app/views/animals/index.html.erb
<body>
  <div class="container center">

  <h1>Pets Available</h1>

    <div class="row">
      <form class="input_field col s12" action="/animals" method="GET"> 
        <div class="row">
          <div class="input_field col s12">
            <input placeholder="Busca por raça" id="search_input" name="by_breed" type="text" width="20%">
              <label for="search"> 
                <button class="btn-floating waves-effect waves-light" id="search_button" type="submit"onclick="Materialize.toast('Busca Realizada!', 8000)"><i class="small material-icons right">search</i>
                </button> 
              </label>

              <input placeholder="Busca por endereco" id="search_input" name="by_address" type="text" width="20%">
              <label for="search"> 
                <button class="btn-floating waves-effect waves-light" id="search_button" type="submit"onclick="Materialize.toast('Busca Realizada!', 8000)"><i class="small material-icons right">search</i>
                </button> 
              </label>


          </div>
            <form>
            <div class="switch right">
            <label >
              All
              <%= check_box "", :only_available, {:onclick=>"Materialize.toast('Filter changed!',1000)",:checked=>""}, true, false %>
              <span class="lever"></span>
              Only Available
              <%= submit_tag 'Refresh', id: "refresh_only_adopted", :class=>"btn" %>
            </label>
            </div>
            </form>
        </div>
      </form>
    </div>

  </div>
  <ul class="collection">
  <% @filtered.each do |animal| %>
      <li class="collection-item avatar">
        <% if animal.attachment? %>
          <img src=<%= animal.attachment.url%> alt="" class="circle">
        <% else %>
          <img src="/assets/dog.jpeg" alt="" class="circle">
        <% end %>
        <span class="title"><%= link_to animal.name, animal %></span>
        <p>Specie: <%= animal.animalType %>
          [<%= animal.breed %>] <br>
          <div class = "right">
          </div>
          Breed: <%= animal.breed %>
          <br>
          Adress: <%= animal.address %>
          <br>
          Age: <%= animal.age %>
          <br>
          Donor: <%= animal.donor %>
        </p>
        <% if animal.adopted %>
          <a href="#!" class="secondary-content"><i class="material-icons">done</i></a>
        <% end %>
      </li>
  <% end %>
  </ul>

  <div class="center">
    <a href='/animals/new'id="download-button" class="btn waves-effect waves-orange teal lighten-1">Share One!</a>
  </div>
</body>

sharepet/app/views/animals/new.html.erb
<div class="center">
<h1>New pet</h1>
<%= render 'form' %>
</div>
<br>
<div class="center">
<a href='/'id="download-button" class="btn waves-effect red">Back</a>
</div>

sharepet/app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" width="20%">
  <div class="card-image">
    <% if @animal.attachment? %>
      <%= image_tag(@animal.attachment.url, {:class=>"activator"}) if @animal.attachment? %>
    <% else %>
      <img src="/assets/dog1.jpeg" alt="" class="activator">
    <% end %>


    <%= link_to image_tag("share-twitter.gif"), "/animals/twitter" %>
 -->

  </div>
  <div class="card-action row">
    <!-- Settings button -->
      <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">settings</i>
        </a>
        <ul>
          <li><%= link_to @animal, confirm: 'Are you sure?', disable_with: 'deleting...', method: :delete, class: 'btn-floating red' do %>
            <i class="material-icons">delete</i>
            <% end %>
          </li>
          <li><a class="btn-floating yellow darken-1"><i class="material-icons">location_on</i></a></li>
          <li><a href="https://gitter.im/ludimila/TrabalhoDAS" class="btn-floating green"><i class="material-icons">forum</i></a></li>
          <li><a href=<%= edit_animal_path(@animal) %> class="btn-floating blue"><i class="material-icons">mode_edit</i></a></li>
        </ul>
      </div>
            
      <%= form_for(@animal) do |f| %>
        <% if @animal.adopted %>
          <%= f.check_box :adopted , :type=>"checkbox", :disabled=>"disabled"%>
          <label for="test5">Adopted</label>
        <% end %>
      <% end %>
    </div>
  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4"><%= @animal.name %><i class="material-icons right">close</i></span>
    <p>
      <b>Specie: </b>
      <%= @animal.animalType %>
    </p>
    <p>
      <b>Breed: </b>
      <%= @animal.breed %>
    </p>
    <p>
      <b>Age: </b>
      <%= @animal.age %>
    </p>
    <p>
      <b>Address: </b>
      <%= @animal.address %>
    </p>
  </div>
  </div>
</div>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@animal.latitude}%2C#{@animal.longitude}" %>

  <div >
    <a href='/animals/' class="btn waves-effect waves-orange red" >Back</a>
  </div>